import Head from "next/head";
import { Inter } from "@next/font/google";
import Navigation from "@/components/Navigation";
import WelcomeSection from "@/components/WelcomeSection";
import StatementSection from "@/components/StatementSection";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>FinanceBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <WelcomeSection />
      <div class="io-container">
        <StatementSection />
      </div>
    </>
  );
}
